### ISSUE TITLE
keepalive?

### ISSUE THREAD

**Issue by unludo** [LogNet/grpc-spring-boot-starter#94]
Hi,
Do you know a way of enabling keepalive with your solution?
Something like indicated in this post:
https://github.com/grpc/grpc-java/issues/3470
Thanks!
Ludovic

**Comment by jvmlet** [comment]
As I understand, the keep alive is configured and provided by client. 
This starter is purely for server side,if you do nothing, the Netty sever will be used. 
Keeping this in mind I suggest you to build the client  channel with appropriate configuration settings.

**Comment by jvmlet** [comment]
If you still experiencing the problem, please open the issue

**Comment by kaiyuanS** [comment]
according to this doc: https://github.com/grpc/grpc/blob/master/doc/keepalive.md#defaults-values
I think we are talking about those GRPC_ARG** configs of this part at the server side.

**Comment by kshchepanovskyi** [comment]
You might use properties:

```
grpc:
  netty-server:
    keep-alive-time: 30s
    keep-alive-timeout: 10s
    permit-keep-alive-time: 30s
    permit-keep-alive-without-calls: true

```
